# Generated by Django 2.2.18 on 2021-03-04 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='bg_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('middle_initial', models.CharField(max_length=3)),
                ('phone_number', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer not to say', 'Prefer Not To Say')], max_length=20)),
                ('insurance_provider', models.CharField(default='Provider', max_length=100)),
                ('insurance_member_id', models.CharField(default='0000000', max_length=25)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('firstname', 'lastname', 'middle_initial', 'email')},
            },
        ),
        migrations.CreateModel(
            name='ec_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('relationship', models.CharField(max_length=20)),
                ('primary_care_physician', models.CharField(max_length=50)),
                ('physician_phone', models.CharField(max_length=10)),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bg_info')),
            ],
            options={
                'unique_together': {('background', 'name')},
            },
        ),
        migrations.CreateModel(
            name='demo_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100)),
                ('apt_unit', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=25)),
                ('zipcode', models.CharField(max_length=5)),
                ('county', models.CharField(choices=[('Worcester', 'Worcester'), ('Wicomico', 'Wicomico'), ('Somerset', 'Somerset'), ('Dorchester', 'Dorchester')], max_length=10)),
                ('state', models.CharField(choices=[('MD', 'Maryland')], max_length=20)),
                ('ethnicity', models.CharField(choices=[('Hispanic or Latino', 'Hispanic or Latino'), ('Not Hispanic or Latino', 'Not Hispanic or Latino'), ('No Response', 'No Response')], max_length=25)),
                ('race', models.CharField(choices=[('American Indian or Alask Native', 'American Indian or Alaska Native'), ('Asian', 'Asian'), ('Black or African American', 'Black or African American'), ('Native Hawaiin or Other Pacific Islander', 'Native Hawaiin or Other Pacific Islander'), ('White', 'White'), ('Two or More Races', 'Two or More Races'), ('No Response', 'No Response')], max_length=50)),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bg_info')),
            ],
            options={
                'unique_together': {('background', 'zipcode', 'street_address')},
            },
        ),
        migrations.CreateModel(
            name='client_notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=10000)),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bg_info')),
            ],
            options={
                'unique_together': {('background', 'notes')},
            },
        ),
    ]
