# Generated by Django 3.1.7 on 2021-06-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='org_image',
            field=models.ImageField(blank=True, null=True, upload_to='org_pics'),
        ),
    ]
