# Generated by Django 2.2.18 on 2021-02-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bg_info',
            name='insurance_member_id',
            field=models.CharField(default='0', max_length=25),
        ),
        migrations.AddField(
            model_name='bg_info',
            name='insurance_provider',
            field=models.CharField(default='Provider', max_length=100),
        ),
    ]
