# Generated by Django 3.1.7 on 2021-06-26 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_organizations_org_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareOrgWith',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaborator', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.organizations')),
            ],
        ),
    ]
