# Generated by Django 2.2.18 on 2021-03-05 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_account_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='group',
        ),
    ]
