# Generated by Django 2.2.18 on 2021-02-14 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210212_1531'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bg_info',
            unique_together={('firstname', 'lastname', 'middle_initial', 'email')},
        ),
        migrations.CreateModel(
            name='ec_contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ec_name', models.CharField(max_length=100)),
                ('relation_to_client', models.CharField(max_length=50)),
                ('ec_primary_phone', models.CharField(max_length=10)),
                ('pcp_name', models.CharField(max_length=100)),
                ('pcp_phone', models.CharField(max_length=10)),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bg_info')),
            ],
        ),
        migrations.CreateModel(
            name='demographics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=50)),
                ('apt_unit_number', models.CharField(blank=True, max_length=5)),
                ('state', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=30)),
                ('zip_code', models.CharField(max_length=5)),
                ('county', models.CharField(choices=[('WO', 'Worcester'), ('WI', 'Wicomico'), ('S', 'Somerset'), ('D', 'Dorchester')], max_length=10)),
                ('marital_status', models.CharField(choices=[('SI', 'Single'), ('M', 'Married'), ('W', 'Widowed'), ('SE', 'Seperated'), ('D', 'Divorced')], max_length=9)),
                ('ethnicity', models.CharField(choices=[('HI', 'Hispanic or Latino'), ('NT', 'Not Hispanic or Lation'), ('NR', 'No Response')], max_length=30)),
                ('race', models.CharField(choices=[('AI', 'American Indian or Alaska Native'), ('AS', 'Asian'), ('AM', 'Black or African American'), ('PI', 'Native Hawaiian or Other Pacific Islander'), ('WH', 'White'), ('MI', 'Two or More Races'), ('NO', 'No Response')], max_length=50)),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bg_info')),
            ],
            options={
                'unique_together': {('background', 'street_address', 'zip_code')},
            },
        ),
    ]
