# Generated by Django 2.2.18 on 2021-02-14 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210214_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographics',
            name='background',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bg_info'),
        ),
        migrations.AlterField(
            model_name='ec_contact',
            name='background',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bg_info'),
        ),
    ]
