# Generated by Django 3.1.7 on 2021-07-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210626_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='filedirectory/')),
                ('document_name', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
