# Generated by Django 2.2.18 on 2021-03-06 22:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_client_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_list',
            name='clients',
        ),
        migrations.AddField(
            model_name='client_list',
            name='clients',
            field=models.ManyToManyField(related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
