# Generated by Django 2.2.18 on 2021-03-06 22:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210306_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_list',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
