# Generated by Django 2.2.18 on 2021-03-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210306_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='has_caseworker',
            field=models.BooleanField(default=False),
        ),
    ]
