# Generated by Django 3.1.7 on 2021-07-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210704_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedwithme',
            name='file',
            field=models.ManyToManyField(blank=True, to='app.DirectoryFiles'),
        ),
    ]
