# Generated by Django 3.1.7 on 2021-07-07 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_recentfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecentFile',
        ),
    ]
