# Generated by Django 3.1.7 on 2021-07-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_delete_recentfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='org_fax',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
