# Generated by Django 2.2.18 on 2021-03-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210307_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=100)),
                ('article_descript', models.CharField(max_length=200)),
                ('article_content', models.CharField(max_length=5000)),
            ],
            options={
                'unique_together': {('article_name', 'article_descript')},
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100, unique=True)),
                ('service_descript', models.CharField(max_length=200)),
                ('service_content', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_name', models.CharField(max_length=50, unique=True)),
                ('dir_descript', models.CharField(max_length=200)),
                ('dir_articles', models.ManyToManyField(blank=True, related_name='articles', to='app.Articles')),
                ('dir_services', models.ManyToManyField(blank=True, related_name='services', to='app.Services')),
            ],
        ),
    ]
