# Generated by Django 2.2.18 on 2021-03-20 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_articles_resourcedirectory_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bg_info',
            new_name='BgInfo',
        ),
        migrations.RenameModel(
            old_name='client_list',
            new_name='ClientList',
        ),
        migrations.RenameModel(
            old_name='client_notes',
            new_name='ClientNotes',
        ),
        migrations.RenameModel(
            old_name='demo_info',
            new_name='DemoInfo',
        ),
        migrations.RenameModel(
            old_name='ec_info',
            new_name='EcInfo',
        ),
    ]
