# Generated by Django 3.1.7 on 2021-07-12 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_filefolder_subfolder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filefolder',
            name='subfolder',
        ),
        migrations.AddField(
            model_name='filefolder',
            name='subfolder',
            field=models.ManyToManyField(blank=True, null=True, related_name='_filefolder_subfolder_+', to='app.FileFolder'),
        ),
    ]
