# Generated by Django 2.2.18 on 2021-03-25 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_organizationlisting'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCaseworkers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newcaseworker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewClients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newclient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewClientList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casewrkr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.NewCaseworkers')),
                ('clnts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.NewClients')),
            ],
        ),
    ]
