# Generated by Django 3.1.7 on 2021-07-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20210712_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filefolder',
            name='subfolder',
            field=models.ManyToManyField(blank=True, null=True, related_name='_filefolder_subfolder_+', to='app.FileFolder'),
        ),
    ]
