# Generated by Django 2.2.18 on 2021-03-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20210325_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcedirectory',
            name='dir_services',
        ),
        migrations.AddField(
            model_name='resourcedirectory',
            name='dir_individuals',
            field=models.ManyToManyField(blank=True, related_name='individuals', to='app.IndividualListing'),
        ),
        migrations.AddField(
            model_name='resourcedirectory',
            name='dir_organizations',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='app.OrganizationListing'),
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
