# Generated by Django 3.1.7 on 2021-07-12 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20210712_1924'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileSubFolder',
        ),
    ]
