# Generated by Django 3.1.7 on 2021-07-12 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_delete_filesubfolder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filefolder',
            name='subfolder',
        ),
    ]
