# Generated by Django 2.2.18 on 2021-03-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210328_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationlisting',
            name='website',
            field=models.CharField(default='default.org', max_length=100),
        ),
    ]
