# Generated by Django 3.1.7 on 2021-07-13 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20210712_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesubfolder',
            name='subfolder',
            field=models.ManyToManyField(blank=True, null=True, related_name='_filesubfolder_subfolder_+', to='app.FileSubFolder'),
        ),
    ]
