# Generated by Django 3.1.7 on 2021-04-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_channels_messages_offlinemessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100, unique=True)),
                ('service_descript', models.CharField(max_length=500)),
                ('service_intake_eligibility', models.CharField(max_length=200)),
                ('service_contact_name', models.CharField(max_length=100)),
                ('service_contact_email', models.EmailField(max_length=254)),
                ('service_contact_phone', models.CharField(max_length=10)),
                ('service_contact_address', models.CharField(max_length=100)),
                ('service_city', models.CharField(max_length=25)),
                ('service_zipcode', models.CharField(max_length=5)),
                ('service_county', models.CharField(choices=[('Worcester', 'Worcester'), ('Wicomico', 'Wicomico'), ('Somerset', 'Somerset'), ('Dorchester', 'Dorchester')], max_length=10)),
                ('service_eligibility', models.CharField(choices=[('All Ages', 'All Ages'), ('Children & Youth (17 and under)', 'Children & Youth (17 and under)'), ('Adults (18-60)', 'Adults (18-60)'), ('Seniors (60+)', 'Seniors (60+)')], max_length=75)),
            ],
        ),
    ]
