# Generated by Django 3.1.7 on 2021-07-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_filesubfolder_subfolder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesubfolder',
            name='subfolder',
            field=models.ManyToManyField(blank=True, null=True, to='app.FileSubFolder'),
        ),
    ]
