# Generated by Django 3.1.7 on 2021-04-14 02:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=5000),
            preserve_default=False,
        ),
    ]
