# Generated by Django 3.1.7 on 2021-07-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20210712_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('county', models.CharField(choices=[('Worcester', 'Worcester'), ('Wicomico', 'Wicomico'), ('Somerset', 'Somerset'), ('Dorchester', 'Dorchester')], max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('language', models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish')], max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='organizations',
            name='areas_served',
            field=models.ManyToManyField(blank=True, to='app.Counties'),
        ),
        migrations.AddField(
            model_name='organizations',
            name='languages',
            field=models.ManyToManyField(blank=True, to='app.Languages'),
        ),
    ]
