# Generated by Django 3.1.7 on 2021-04-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_services_service_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcedirectory',
            name='dir_individuals',
        ),
        migrations.RemoveField(
            model_name='resourcedirectory',
            name='dir_organizations',
        ),
        migrations.AddField(
            model_name='resourcedirectory',
            name='dir_services',
            field=models.ManyToManyField(blank=True, related_name='services', to='app.Services'),
        ),
    ]
