# Generated by Django 3.1.7 on 2021-07-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20210714_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filefolder',
            name='subfolder',
            field=models.ManyToManyField(blank=True, to='app.FileSubFolder'),
        ),
        migrations.AlterField(
            model_name='filesubfolder',
            name='subfolder',
            field=models.ManyToManyField(blank=True, to='app.FileSubFolder'),
        ),
    ]
