# Generated by Django 3.1.7 on 2021-04-21 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_chatgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='to_user',
        ),
        migrations.AddField(
            model_name='messages',
            name='chat_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.chatgroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messages',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages_sent', to=settings.AUTH_USER_MODEL),
        ),
    ]
