# Generated by Django 3.1.7 on 2021-07-25 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20210714_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offlinemessage',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='offlinemessage',
            name='to_user',
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='solitary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messages',
            name='is_file',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messages',
            name='is_notice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offlinemessage',
            name='acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offlinemessage',
            name='chat_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.chatgroup'),
        ),
        migrations.AddField(
            model_name='offlinemessage',
            name='offline_user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='offline_from_user', to='app.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='offlinemessage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_messages', to='app.messages'),
        ),
    ]
