# Generated by Django 3.1.7 on 2021-06-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20210627_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
