# Generated by Django 3.1.7 on 2021-08-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20210730_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_org_difficulty', models.CharField(choices=[('Very Easy', 'Very Easy'), ('Easy', 'Easy'), ('Moderate', 'Moderate'), ('Hard', 'Hard'), ('Very Hard', 'Very Hard')], max_length=10)),
                ('add_org_answer', models.CharField(max_length=500)),
                ('add_org_comments', models.CharField(blank=True, max_length=500)),
                ('edit_org_difficulty', models.CharField(choices=[('Very Easy', 'Very Easy'), ('Easy', 'Easy'), ('Moderate', 'Moderate'), ('Hard', 'Hard'), ('Very Hard', 'Very Hard')], max_length=10)),
                ('edit_org_answer', models.CharField(max_length=500)),
                ('edit_org_comments', models.CharField(blank=True, max_length=500)),
                ('find_org_difficulty', models.CharField(choices=[('Very Easy', 'Very Easy'), ('Easy', 'Easy'), ('Moderate', 'Moderate'), ('Hard', 'Hard'), ('Very Hard', 'Very Hard')], max_length=10)),
                ('find_org_answer', models.CharField(max_length=500)),
                ('find_org_comments', models.CharField(blank=True, max_length=500)),
                ('add_folder_file_difficulty', models.CharField(choices=[('Very Easy', 'Very Easy'), ('Easy', 'Easy'), ('Moderate', 'Moderate'), ('Hard', 'Hard'), ('Very Hard', 'Very Hard')], max_length=10)),
                ('add_folder_file_answer', models.CharField(max_length=500)),
                ('add_folder_file_comments', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='myfilename',
            name='newname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
