# Generated by Django 3.1.7 on 2021-04-22 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20210422_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='chat_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.chatgroup'),
        ),
    ]
