# Generated by Django 3.1.7 on 2021-08-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20210807_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysurvey',
            name='add_folder_file_answer',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mysurvey',
            name='add_folder_file_comments',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='mysurvey',
            name='add_org_answer',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mysurvey',
            name='add_org_comments',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='mysurvey',
            name='edit_org_answer',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mysurvey',
            name='edit_org_comments',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='mysurvey',
            name='find_org_answer',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mysurvey',
            name='find_org_comments',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
