# Generated by Django 3.1.7 on 2021-04-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20210422_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bgColor',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
