# Generated by Django 3.1.7 on 2021-08-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20210809_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysurvey',
            name='add_org_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mysurvey2',
            name='edit_org_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mysurvey3',
            name='find_org_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mysurvey4',
            name='add_folder_file_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
