# Generated by Django 3.1.7 on 2021-09-09 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20210809_1400'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articles',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='MySurvey',
        ),
        migrations.DeleteModel(
            name='MySurvey2',
        ),
        migrations.DeleteModel(
            name='MySurvey3',
        ),
        migrations.DeleteModel(
            name='MySurvey4',
        ),
        migrations.RemoveField(
            model_name='resourcedirectory',
            name='dir_articles',
        ),
        migrations.RemoveField(
            model_name='resourcedirectory',
            name='dir_services',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='testtags',
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
        migrations.DeleteModel(
            name='ResourceDirectory',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
