# Generated by Django 3.1.7 on 2021-07-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20210701_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='solitary',
            field=models.BooleanField(default=False),
        ),
    ]
