# Generated by Django 3.1.7 on 2021-07-20 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_chatgroup_solitary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offlinemessage',
            old_name='to_user',
            new_name='offline_user',
        ),
        migrations.AlterField(
            model_name='offlinemessage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offline_messages', to='app.messages'),
        ),
    ]
