# Generated by Django 3.1.7 on 2021-07-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_remove_offlinemessage_from_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='is_notice',
            field=models.BooleanField(default=False),
        ),
    ]
