# Generated by Django 3.1.7 on 2021-09-09 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_priority_tasks'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tasks',
            unique_together={('assigner', 'title', 'description')},
        ),
    ]
