# Generated by Django 3.1.7 on 2021-09-09 20:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20210909_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='assignees',
        ),
        migrations.AddField(
            model_name='tasks',
            name='assignees',
            field=models.ManyToManyField(related_name='assignee', to=settings.AUTH_USER_MODEL),
        ),
    ]
