# Generated by Django 3.1.7 on 2021-07-21 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_messages_is_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlinemessage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_messages', to='app.messages'),
        ),
        migrations.AlterField(
            model_name='offlinemessage',
            name='offline_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_from_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
