# Generated by Django 3.1.7 on 2021-07-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20210721_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinemessage',
            name='acknowledged',
            field=models.BooleanField(default=False),
        ),
    ]
