# Generated by Django 3.1.7 on 2021-07-22 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_offlinemessage_acknowledged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='is_link',
        ),
    ]
