# Generated by Django 3.1.7 on 2021-09-15 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_account_is_online'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priority',
            old_name='difficulty',
            new_name='priority',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='difficulty',
            new_name='priority',
        ),
    ]
