# Generated by Django 3.1.6 on 2021-09-20 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_account_is_online'),
        ('app', '0041_account_is_online'),
    ]

    operations = [
    ]
