# Generated by Django 3.1.7 on 2021-09-24 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_account_is_online'),
        ('app', '0042_auto_20210915_1552'),
    ]

    operations = [
    ]
