# Generated by Django 3.1.7 on 2021-10-25 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_merge_20211015'),
    ]

    operations = [
    ]
