# Generated by Django 3.1.7 on 2021-10-25 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_merge_20211015'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='first_name',
            field=models.CharField(default='Kutter', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='last_name',
            field=models.CharField(default='Aaron', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
