# Generated by Django 3.1.7 on 2021-10-25 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20211024_2029'),
        ('app', '0045_auto_20211024_2027'),
        ('app', '0042_auto_20211024_2038'),
        ('app', '0043_auto_20211024_2028'),
    ]

    operations = [
    ]
